services:
  backend:
    build:
      context: .              # Контекст сборки
      dockerfile: Dockerfile   # Dockerfile
    container_name: movie-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]  
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: movie-test
    depends_on:
      - backend
    command: >
      /bin/sh -c "sleep 10 && pytest tests"  # Задержка перед запуском тестов
      
volumes:
  postgres-data:
